[package]
name = "notes"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
diesel = { version = "1.4.4", features = ["postgres", "chrono"] }
clap = { version = "3.2.5", features = ["derive"] }
dotenv = "^0.15.0"
colored = "2.0.0"
